services:
  # Web service for the Paired application
  - type: web
    name: paired-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
    # Add build arguments for frontend to fix CORS issues
    dockerBuildArgs:
      - VITE_API_URL=/api/v1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: paired-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: paired-redis
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      # Add other environment variables from your .env file here
      # For example:
      # - key: GOOGLE_API_KEY
      #   value: your_google_api_key

  # Redis instance for caching
  - type: redis
    name: paired-redis
    ipAllowList: [] # Allow all
    maxmemoryPolicy: allkeys-lru

databases:
  # PostgreSQL database
  - name: paired-postgres
    ipAllowList: [] # Allow all
    postgresMajorVersion: 15 